# Generated by Django 4.0 on 2022-05-23 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0006_post_snippet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='snippet',
            field=models.CharField(blank=True, default='Post the article snippet here', max_length=250, null=True),
        ),
    ]
