# Generated by Django 4.0 on 2022-05-23 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0007_alter_post_snippet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='snippet',
            field=models.CharField(blank=True, default='Click link above to read post', max_length=250, null=True),
        ),
    ]
