# Generated by Django 4.0 on 2022-05-25 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0011_prof_inf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prof_inf',
            name='bio',
            field=models.TextField(max_length=500),
        ),
    ]
